language: haskell

ghc:
  - 7.8.4
  - 7.6.3
  - 7.4.2

install:
  - cabal update
  - cabal install cabal-install
  - cabal install --enable-tests --only-dependencies

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal install
  - cabal haddock
  - cabal test --show-details=streaming

matrix:
  fast_finish: true
  allow_failures:
    - ghc: 7.6.3
    - ghc: 7.4.2

branches:
  only:
    - master

notifications:
  email: false
